# 1. Bài tập thực hành

# Bài 1. Tạo Tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [2]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


**Yêu cầu:** Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [3]:
print("Kích thước (shape):", a.shape)
print("Số chiều (ndim):", a.ndim)
print("Kiểu dữ liệu (dtype):", a.dtype)

Kích thước (shape): torch.Size([2, 3])
Số chiều (ndim): 2
Kiểu dữ liệu (dtype): torch.int32


# Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [4]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.5804, 0.8289, 0.7927, 0.7565],
        [0.0773, 0.5461, 0.7463, 0.5187],
        [0.2194, 0.4431, 0.7412, 0.7493]])
tensor([[-1.1882,  0.1037,  0.7365, -0.4905],
        [ 0.2846, -0.2491, -0.2264, -0.6581],
        [-0.2523,  0.7133, -0.3873,  1.2102]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Yêu cầu:** Nhận xét sự khác nhau giữa torch.rand() và torch.randn().

In [5]:
# Kiểm chứng trên mẫu lớn: rand ~ U[0, 1), randn ~ N(0, 1)
r = torch.rand(100000)
n = torch.randn(100000)
print("rand : min = %.4f, max = %.4f, mean = %.4f, std = %.4f" % (r.min(), r.max(), r.mean(), r.std()))
print("randn: min = %.4f, max = %.4f, mean = %.4f, std = %.4f" % (n.min(), n.max(), n.mean(), n.std()))

rand : min = 0.0000, max = 1.0000, mean = 0.5002, std = 0.2887
randn: min = -4.1929, max = 4.2056, mean = 0.0062, std = 0.9999


**Yêu cầu:** Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

In [6]:
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


# Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [7]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4]).

# Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [9]:
import torch

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.1965, -0.8694, -0.6403,  1.0336, -1.5355],
         [-0.9781,  1.3758,  0.6903,  0.9339,  1.9901],
         [-1.1105, -0.8882,  1.2891,  0.5382, -1.0551],
         [-0.8612, -0.0024,  0.9305, -0.3769,  0.5945]],

        [[-0.6691,  0.9529, -1.3585,  0.5238, -2.2224],
         [ 0.5575,  0.2740, -0.0294, -0.1044, -0.4500],
         [-0.8020, -0.4835, -0.3220,  1.4015,  0.8995],
         [ 0.6136, -1.1208, -0.0243,  1.0632, -0.4177]],

        [[-0.0535,  1.8072, -1.0822,  0.4091,  0.3992],
         [ 0.8570,  1.0955, -1.0357,  0.8943, -0.3918],
         [-0.0189, -0.5850, -0.3781,  0.3982, -0.3621],
         [-1.4929, -0.1369,  0.8309,  0.3884,  1.3461]]])

Tensor a[1]:
tensor([[-0.6691,  0.9529, -1.3585,  0.5238, -2.2224],
        [ 0.5575,  0.2740, -0.0294, -0.1044, -0.4500],
        [-0.8020, -0.4835, -0.3220,  1.4015,  0.8995],
        [ 0.6136, -1.1208, -0.0243,  1.0632, -0.4177]])

Tensor a[1:, 2:4]:
tensor([[[-0.8020, -0.4835, -0.3220,  1.4015,  0.8

**Yêu cầu:** Cho biết shape của a[1] và a[1:, 2:4].

In [10]:
print("a[1].shape      =", a[1].shape)
print("a[1:, 2:4].shape =", a[1:, 2:4].shape)

a[1].shape      = torch.Size([4, 5])
a[1:, 2:4].shape = torch.Size([2, 2, 5])


**Yêu cầu:** Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [11]:
last2 = a[:, :, -2:]
print(last2)
print("Shape:", last2.shape)

tensor([[[ 1.0336, -1.5355],
         [ 0.9339,  1.9901],
         [ 0.5382, -1.0551],
         [-0.3769,  0.5945]],

        [[ 0.5238, -2.2224],
         [-0.1044, -0.4500],
         [ 1.4015,  0.8995],
         [ 1.0632, -0.4177]],

        [[ 0.4091,  0.3992],
         [ 0.8943, -0.3918],
         [ 0.3982, -0.3621],
         [ 0.3884,  1.3461]]])
Shape: torch.Size([3, 4, 2])


# Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [12]:
import torch

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 1.7615,  0.1621, -0.2349,  0.4316],
        [ 0.4015, -0.2944,  0.9456, -1.2111],
        [-0.2548,  0.5393, -0.0253,  0.9823]])

Flatten:
tensor([ 1.7615,  0.1621, -0.2349,  0.4316,  0.4015, -0.2944,  0.9456, -1.2111,
        -0.2548,  0.5393, -0.0253,  0.9823])

Reshape to 3 x 2 x 2:
tensor([[[ 1.7615,  0.1621],
         [-0.2349,  0.4316]],

        [[ 0.4015, -0.2944],
         [ 0.9456, -1.2111]],

        [[-0.2548,  0.5393],
         [-0.0253,  0.9823]]])


**Yêu cầu:** Kiểm tra số phần tử trước và sau khi reshape.

In [13]:
print("Số phần tử ban đầu     :", a.numel())
print("Sau ravel()            :", a.ravel().numel())
print("Sau reshape(3, 2, 2)   :", a.reshape(3, 2, 2).numel())

Số phần tử ban đầu     : 12
Sau ravel()            : 12
Sau reshape(3, 2, 2)   : 12


**Yêu cầu:** Thử reshape Tensor thành kích thước 2 × 6.

In [14]:
b = a.reshape(2, 6)
print(b)
print("Shape:", b.shape)

tensor([[ 1.7615,  0.1621, -0.2349,  0.4316,  0.4015, -0.2944],
        [ 0.9456, -1.2111, -0.2548,  0.5393, -0.0253,  0.9823]])
Shape: torch.Size([2, 6])


# Bài 6. Phép toán và nhân ma trận
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [15]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 1.3287,  0.4807,  1.4692],
        [-0.0066,  1.6858,  0.9767]])
b:
tensor([[-0.0715,  0.7045,  0.5689],
        [ 1.5888,  0.9552,  0.6865]])

a + b:
tensor([[1.2571, 1.1852, 2.0381],
        [1.5822, 2.6409, 1.6632]])

a / b:
tensor([[-1.8571e+01,  6.8241e-01,  2.5826e+00],
        [-4.1773e-03,  1.7649e+00,  1.4228e+00]])

a^2:
tensor([[1.7653e+00, 2.3112e-01, 2.1586e+00],
        [4.4051e-05, 2.8418e+00, 9.5399e-01]])

Matrix multiplication:
tensor([[1.0795, 3.5788],
        [1.7437, 2.2702]])


**Yêu cầu:** Phân biệt phép toán a * b với a @ b.T.

In [16]:
print("a * b (nhân từng phần tử):")
print(a * b)
print("Shape:", (a * b).shape)

print("\na @ b.T (nhân ma trận):")
print(a @ b.T)

# Phần tử [0, 0] của a @ b.T bằng tổng hàng 0 của a * b
print("\nKiểm tra: (a @ b.T)[0, 0] =", (a @ b.T)[0, 0].item(),
      "| (a * b)[0].sum() =", (a * b)[0].sum().item())

a * b (nhân từng phần tử):
tensor([[-0.0951,  0.3387,  0.8358],
        [-0.0105,  1.6102,  0.6705]])
Shape: torch.Size([2, 3])

a @ b.T (nhân ma trận):
tensor([[1.0795, 3.5788],
        [1.7437, 2.2702]])

Kiểm tra: (a @ b.T)[0, 0] = 1.0794544219970703 | (a * b)[0].sum() = 1.0794544219970703


**Yêu cầu:** Cho biết shape của kết quả a @ b.T.

In [17]:
print("a.shape   =", a.shape)
print("b.T.shape =", b.T.shape)
print("(a @ b.T).shape =", (a @ b.T).shape)

a.shape   = torch.Size([2, 3])
b.T.shape = torch.Size([3, 2])
(a @ b.T).shape = torch.Size([2, 2])


# Bài 7. Các hàm thống kê trên Tensor
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [18]:
import torch

a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.0209, -0.1867, -0.0242,  0.3256],
        [-1.7013, -0.5650, -0.5685, -1.8420],
        [-0.0866, -0.2726, -1.4030,  0.7040]])

Mean:
tensor([-0.6029, -0.3414, -0.6652, -0.2708])

Standard deviation:
tensor([0.9518, 0.1983, 0.6944, 1.3738])

Cumulative sum:
tensor([[-0.0209, -0.1867, -0.0242,  0.3256],
        [-1.7222, -0.7517, -0.5927, -1.5164],
        [-1.8088, -1.0242, -1.9957, -0.8124]])


**Yêu cầu:** Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

In [19]:
print("Mean (dim=1):")
print(torch.mean(a, dim=1))

print("\nStandard deviation (dim=1):")
print(torch.std(a, dim=1))

print("\nCumulative sum (dim=1):")
print(torch.cumsum(a, dim=1))

print("\nShape mean dim=0:", torch.mean(a, dim=0).shape,
      "| Shape mean dim=1:", torch.mean(a, dim=1).shape)

Mean (dim=1):
tensor([ 0.0234, -1.1692, -0.2645])

Standard deviation (dim=1):
tensor([0.2158, 0.6980, 0.8691])

Cumulative sum (dim=1):
tensor([[-0.0209, -0.2076, -0.2318,  0.0938],
        [-1.7013, -2.2663, -2.8348, -4.6767],
        [-0.0866, -0.3592, -1.7621, -1.0581]])

Shape mean dim=0: torch.Size([4]) | Shape mean dim=1: torch.Size([3])


# Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [20]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


**Yêu cầu:** Tính thủ công đạo hàm của y = x² tại x = 3.6 và so sánh với x.grad.

In [21]:
manual = 2 * 3.6
print("Đạo hàm thủ công: dy/dx = 2x =", manual)
print("x.grad (autograd):", x.grad.item())
print("Trùng khớp:", abs(manual - x.grad.item()) < 1e-5)

Đạo hàm thủ công: dy/dx = 2x = 7.2
x.grad (autograd): 7.199999809265137
Trùng khớp: True


**Yêu cầu:** Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

In [22]:
x = torch.tensor(3.6, requires_grad=True)
y = 3 * x**2 + 2 * x + 1
y.backward()

manual = 6 * 3.6 + 2
print("y =", y.item())
print("x.grad (autograd):", x.grad.item())
print("Thủ công: dy/dx = 6x + 2 =", manual)
print("Trùng khớp:", abs(manual - x.grad.item()) < 1e-4)

y = 47.07999801635742
x.grad (autograd): 23.599998474121094
Thủ công: dy/dx = 6x + 2 = 23.6
Trùng khớp: True


# Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức y = x² + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [23]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.7083],
        [ 0.7063],
        [-0.0721]], requires_grad=True)
Learned coefficients:
tensor([[1.0013],
        [2.0038],
        [2.9024]], requires_grad=True)


**Yêu cầu:** So sánh ba hệ số học được với [1, 2, 3].

In [24]:
true_w = torch.tensor([1.0, 2.0, 3.0])
learned = w.detach().ravel()
print("Hệ số thật    :", true_w.tolist())
print("Hệ số học được:", [round(v, 4) for v in learned.tolist()])
print("Sai lệch tuyệt đối:", [round(v, 4) for v in (learned - true_w).abs().tolist()])
print("MSE cuối cùng:", mse.item())

Hệ số thật    : [1.0, 2.0, 3.0]
Hệ số học được: [1.0013, 2.0038, 2.9024]
Sai lệch tuyệt đối: [0.0013, 0.0038, 0.0976]
MSE cuối cùng: 0.00678423885256052


**Yêu cầu:** Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

# Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [25]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.7171, requires_grad=True)
B = tensor(4.2828, requires_grad=True)
C = tensor(3.2828, requires_grad=True)
D = tensor(2.2828, requires_grad=True)


**Yêu cầu:** Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.

In [26]:
with torch.no_grad():
    print("A + B =", round((A + B).item(), 4), " (cần = 9)")
    print("C - D =", round((C - D).item(), 4), " (cần = 1)")
    print("A + C =", round((A + C).item(), 4), " (cần = 8)")
    print("B - D =", round((B - D).item(), 4), " (cần = 2)")
    print("Tổng sai số bình phương:", sqerr.item())

A + B = 8.9999  (cần = 9)
C - D = 1.0  (cần = 1)
A + C = 8.0  (cần = 8)
B - D = 2.0  (cần = 2)
Tổng sai số bình phương: 4.092555627721595e-09


**Yêu cầu:** Nhận xét vì sao bài toán có thể có nhiều nghiệm.

In [27]:
# Hạng của ma trận hệ số (các cột ứng với A, B, C, D)
M = torch.tensor([[1., 1., 0., 0.],    # A + B = 9
                  [0., 0., 1., -1.],   # C - D = 1
                  [1., 0., 1., 0.],    # A + C = 8
                  [0., 1., 0., -1.]])  # B - D = 2
print("Số ẩn:", M.shape[1], "| Hạng ma trận hệ số:", torch.linalg.matrix_rank(M).item())

# Họ nghiệm tổng quát: D = t, C = 1 + t, B = 2 + t, A = 7 - t
for t in [0.0, 1.0, 2.5]:
    a_, b_, c_, d_ = 7 - t, 2 + t, 1 + t, t
    print(f"t = {t}: A = {a_}, B = {b_}, C = {c_}, D = {d_} ->",
          a_ + b_, c_ - d_, a_ + c_, b_ - d_)

Số ẩn: 4 | Hạng ma trận hệ số: 3
t = 0.0: A = 7.0, B = 2.0, C = 1.0, D = 0.0 -> 9.0 1.0 8.0 2.0
t = 1.0: A = 6.0, B = 3.0, C = 2.0, D = 1.0 -> 9.0 1.0 8.0 2.0
t = 2.5: A = 4.5, B = 4.5, C = 3.5, D = 2.5 -> 9.0 1.0 8.0 2.0


# 2. Bài tập áp dụng

# Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau

## a) Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

In [28]:
import torch

X = torch.arange(24)
print("X:", X)
print("Số phần tử:", X.numel())

X1 = X.reshape(4, 6)
print("\nReshape 4 x 6:")
print(X1)
print("Shape:", X1.shape)

X2 = X.reshape(2, 12)
print("\nReshape 2 x 12:")
print(X2)
print("Shape:", X2.shape)

X3 = X.reshape(2, 3, 4)
print("\nReshape 2 x 3 x 4:")
print(X3)
print("Shape:", X3.shape)

X: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
Số phần tử: 24

Reshape 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
Shape: torch.Size([4, 6])

Reshape 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
Shape: torch.Size([2, 12])

Reshape 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape: torch.Size([2, 3, 4])


## b) Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [29]:
import torch

torch.manual_seed(42)   # cố định để kết quả tái lập được

A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A:")
print(A)
print("B:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B (nhân từng phần tử):")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột của A (dim=0):")
print(torch.mean(A, dim=0))
print("Trung bình theo cột của B (dim=0):")
print(torch.mean(B, dim=0))

print("\nĐộ lệch chuẩn theo cột của A (dim=0):")
print(torch.std(A, dim=0))
print("Độ lệch chuẩn theo cột của B (dim=0):")
print(torch.std(B, dim=0))

A:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
B:
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])

A + B:
tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])

A * B (nhân từng phần tử):
tensor([[ 0.3738, -0.2177, -0.2319,  0.2207],
        [-1.4846, -0.1523, -1.6911,  0.4789],
        [ 0.6244,  0.1835, -0.1753,  0.6434]])

A / B:
tensor([[ 0.3032, -0.0762, -0.2371,  0.2404],
        [-0.8493, -0.2280, -2.8834,  0.8500],
        [ 0.3413,  0.3895, -1.6320,  1.0181]])

Trung bình theo cột của A (dim=0):
tensor([-0.1082,  0.0699,  0.9925,  0.1339])
Trung bình theo cột của B (dim=0):
tensor([ 1.2617, -0.0621, -0.6942,  0.3341])

Độ lệch chuẩn theo cột của A (dim=0):
tensor([0.8810, 0.2325, 1.0635, 0.7285])
Độ lệch chuẩn 

## c) Cho y = 2x² + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [30]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("y(2) =", y.item())
print("dy/dx bằng autograd:", x.grad.item())

# Thủ công: dy/dx = 4x + 5 -> tại x = 2: 4*2 + 5 = 13
manual = 4 * 2 + 5
print("dy/dx thủ công (4x + 5):", manual)
print("Trùng khớp:", x.grad.item() == manual)

y(2) = 21.0
dy/dx bằng autograd: 13.0
dy/dx thủ công (4x + 5): 13
Trùng khớp: True


## d) Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [31]:
import numpy as np
import torch

np.random.seed(0)
torch.manual_seed(0)

polynomial = np.poly1d([2, -3, 5])   # y = 2x^2 - 3x + 5
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)


def train(lr, epochs):
    w = torch.randn(3, 1, requires_grad=True)
    optimizer = torch.optim.NAdam([w], lr=lr)
    for epoch in range(epochs):
        optimizer.zero_grad()
        y_pred = x @ w
        mse = torch.mean(torch.square(y - y_pred))
        mse.backward()
        optimizer.step()
    return w.detach().ravel(), mse.item()


# Lần 1: giữ nguyên tham số như Bài 9 (lr = 0.01, 1000 epoch)
w1, mse1 = train(lr=0.01, epochs=1000)
print("lr = 0.01, 1000 epoch:")
print("  Hệ số tìm được:", [round(v, 4) for v in w1.tolist()])
print("  MSE:", round(mse1, 6))

# Lần 2: tăng learning rate và số epoch để hội tụ tốt hơn
w2, mse2 = train(lr=0.1, epochs=3000)
print("\nlr = 0.1, 3000 epoch:")
print("  Hệ số tìm được:", [round(v, 4) for v in w2.tolist()])
print("  MSE:", mse2)

print("\nHệ số thật: [2, -3, 5]")

lr = 0.01, 1000 epoch:
  Hệ số tìm được: [2.0137, -2.9577, 3.7122]
  MSE: 1.051446

lr = 0.1, 3000 epoch:
  Hệ số tìm được: [2.0, -3.0, 5.0]
  MSE: 4.425260158313904e-11

Hệ số thật: [2, -3, 5]
